# icglue keep begin testcaselist
TESTCASES := \
	ff.tc_sanity \
	ff_real.tc_sanity \
	dummy.tc_sanity \

# icglue keep end

# icglue keep begin cleanup
OLDAFTERDAYS := 10
# icglue keep end

include ${ICPRO_DIR}/env/regression/Makefile.regression
