# icglue keep begin testcaselist
TESTCASES := \
	ff.tc_sanity \
	ff_real.tc_sanity \
	dummy.tc_sanity \
	dummy.tc_events_1 \
	dummy.tc_events_2 \

# icglue keep end

# icglue keep begin cleanup
OLDAFTERDAYS := 10
# icglue keep end

include ${ICPRO_DIR}/env/regression/Makefile.regression
