# icglue keep begin testcaselist
TESTCASES := \
	ff.tc_sanity \
	ff_real.tc_sanity \
	dummy.tc_sanity \
	dummy.tc_events_1 \
	dummy.tc_events_2 \
	dummy.tc_events_3 \
	dummy.tc_cleanup_simple \
	dummy.tc_cleanup_ptr1 \
	dummy.tc_cleanup_ptr2 \
	dummy.tc_cleanup_stack \
	dummy_c.tc_sanity \
	iotest.tc_sanity \

# icglue keep end

# icglue keep begin cleanup
OLDAFTERDAYS := 10
# icglue keep end

include ${ICPRO_DIR}/env/regression/Makefile.regression
