name: "Test"

on:
  push:
    branches:
      - test
      - master
      - 1.x
    pull_request:

jobs:
  linux:
    name: "Test Linux/Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-upgrade clang cmake g++ gcc iverilog libboost-coroutine-dev libpcl1 libpcl1-dev make valgrind
      - name: "Build library with gcc"
        env:
          CC: gcc
          CXX: g++
        run: |
          ./configure --clean --enable-strict-warning
          make -j3
      - name: "Build library with clang"
        env:
          CC: clang
          CXX: clang++
        run: |
          ./configure --clean --enable-strict-warning
          make -j3
      - name: "Run tests with libco coroutines, default cc"
        run: |
          ./configure --clean --thread-implementation=libco-local
          make -j3
          make test
      - name: "Run tests with pcl coroutines, default cc"
        run: |
          ./configure --clean --thread-implementation=pcl
          make -j3
          make test
      - name: "Run tests with boost1 coroutines, default cc"
        run: |
          ./configure --clean --thread-implementation=boost1
          make -j3
          make test
      - name: "Run tests with boost2 coroutines, default cc"
        run: |
          ./configure --clean --thread-implementation=boost2
          make -j3
          make test
