name: "Test"

on:
  push:
    branches:
      - test
      - master
      - 1.x
    pull_request:

jobs:
  linux:
    name: "Test Linux/Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-upgrade clang g++ gcc iverilog libboost-coroutine-dev libpcl1 libpcl1-dev make valgrind
      - name: "Build library with gcc"
        env:
          CC: gcc
          CXX: g++
        run: |
          make cleanlib
          make -j3
      - name: "Build library with clang"
        env:
          CC: clang
          CXX: clang++
        run: |
          make cleanlib
          make -j3
      - name: "Run tests with pcl coroutines, gcc"
        env:
          CC: gcc
          CXX: g++
          THREAD_IMPL: pcl
        run: |
          make cleanall
          make -j3 test
      - name: "Run tests with pcl coroutines, clang"
        env:
          CC: clang
          CXX: clang++
          THREAD_IMPL: pcl
        run: |
          make cleanall
          make -j3 test
      - name: "Run tests with boost1 coroutines, default cc"
        env:
          THREAD_IMPL: boost1
        run: |
          make cleanall
          make -j3 test
      - name: "Run tests with boost2 coroutines, default cc"
        env:
          THREAD_IMPL: boost2
        run: |
          make cleanall
          make -j3 test
